### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by r3v1** [xpublish-community/xpublish#100]
Hi, 

how do I add FastAPI authentication features to the endpoint calls?

Thanks

**Comment by davidbrochart** [comment]
[FastAPI-Users](https://github.com/fastapi-users/fastapi-users) does a lot of heavy-lifting for authentication and user management. That's what we use in [jupyverse](https://github.com/jupyter-server/jupyverse).

**Comment by jhamman** [comment]
This has sat for a long time so I'm going to close this out. The approach I would take here is to apply auth as a middleware layer on top of the Xpublish FastAPI App.
