### ISSUE TITLE
OpenDAP endpoint

### ISSUE THREAD

**Issue by jhamman** [xpublish-community/xpublish#105]
I recently learned about [zarrdap](https://github.com/NCEI-NOAAGov/zarrdap). ZarrDAP is a FastAPI project that provides access to Zarr and NetCDF data in remote object storage using the Open-source Project for a Network Data Access Protocol (OPeNDAP).

This has me wondering if we can plug in the xarray opendap handler here. @markccapece, wondering if you have run across xpublish before and if you have thoughts on how the xarray handler in zarrdap could be used outside of zarrdap?

xref: #50

**Comment by abkfenris** [comment]
I've got the start of a xpublish compatible OpenDAP router at https://github.com/gulfofmaine/xpublish-opendap

**Comment by jhamman** [comment]
@abkfenris - thanks for sharing! I plan to take a look at what you've written this week. Do you have any interest in adding this as a router to this project?

**Comment by xaviernogueira** [comment]
@abkfenris can this be closed with the existence of [`xpublish-opendap`](https://github.com/xpublish-community/xpublish-opendap)?

**Comment by abkfenris** [comment]
Thanks @xaviernogueira , yes this and a few other issues can be closed by pointing to specific plugins now.
