### ISSUE TITLE
Pydantic 2 support

### ISSUE THREAD

**Issue by abkfenris** [xpublish-community/xpublish#214]
Ruh-row, it looks like we've been bitten by a Pydantic 2 change.

_Originally posted by @abkfenris in https://github.com/xpublish-community/xpublish/issues/213#issuecomment-1635656104_
            

It appears that we may need some tweaks for Pydantic 2 support. 

https://github.com/xpublish-community/xpublish/actions/runs/5553093015/jobs/10141236050?pr=213#step:6:114

- https://docs.pydantic.dev/dev-v2/usage/errors/#model-field-overridden
- https://docs.pydantic.dev/dev-v2/migration/

**Comment by abkfenris** [comment]
I think it may be that we need to annotate any fields that we've overridden, like `name` on plugins.

https://github.com/xpublish-community/xpublish/blob/b425bc1fb5125e79d747827a2a7d73910fd2d9b4/tests/test_rest_api.py#L66-L76

becomes

```py
 class AirtempPlugin(Plugin): 
     name: str = 'airtemp' 
  
     @hookimpl 
     def get_dataset(self, dataset_id: str): 
         if dataset_id == 'airtemp': 
             return airtemp_ds 
  
     @hookimpl 
     def get_datasets(self): 
         return ['airtemp'] 
```

**Comment by xaviernogueira** [comment]
I just noticed this! I'm on it. Will have it done today or tomarrow.

**Comment by xaviernogueira** [comment]
Just made a pull request #215. Mind checking it out when you have the chance?

I can't run the full pre-commit on my system (nodejs error), so if you could pull down my branch and run the pre-commit that would be great.

Also the tests are failing rn. Not entirely sure why going to work on that of course before I switch it from a Draft to Full PR.

**Comment by abkfenris** [comment]
I just started taking a look. At a quick glance at the failures, a bunch are from using `|` for unions which is syntax that got added in 3.10, and we are still supporting 3.9.

For the pre-commit, you can make a comment with "pre-commit.ci autofix" on the PR, and pre-commit.ci will push the changes from Ruff back onto your branch and you can pull those back down. https://results.pre-commit.ci/run/github/235846200/1689788417.B7uBcS6vRRy61WJYv_tI8Q

**Comment by xaviernogueira** [comment]
Should we issue a bug fix release so it can auto build PyPI? Or do you want to wait for the backwards compatibility tests to be added?

**Comment by abkfenris** [comment]
I tried cutting a release, but PyPI has made some changes that has caused it to fail. I'm working with Joe on getting them fixed.

**Comment by xaviernogueira** [comment]
Sounds good. In case it's useful have a release -> PyPI workflow that worked very recently [here](https://github.com/xaviernogueira/Tabular_ML/blob/main/.github/workflows/publish_to_pypi.yml).

We used different build commands:
* I used `python -m build --sdist --wheel . --outdir dist` after installing and upgrading pip to python 3.11.
* I didn't use twine, as I remember having issues with it, and instead used a specific version of `pypa/gh-action-pypi-publish`

```
    - name: Build package
      run: python -m build --sdist --wheel . --outdir dist

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_PASSWORD }}
```

**Comment by abkfenris** [comment]
There were some pretty similar steps previously, but it looks like PyPI just made more folks need to have 2 factor auth enabled. Instead I've moved things to use the trusted publisher system, and ended up moving from setup.py to pyproject.toml at the same time (can't remember how to fix things in setup.py, but can remember how to migrate them).

Mind taking a look?  #218

**Comment by xaviernogueira** [comment]
Just seeing this now. Seems like you made the merge? Let me know if you still want me to look at it.

**Comment by abkfenris** [comment]
Thanks, hopefully [this time](https://github.com/xpublish-community/xpublish/actions/runs/5624294627/job/15240822478) will work, otherwise I may ping you to get more eyeballs on why the release isn't working.

**Comment by abkfenris** [comment]
No need for the bat signal, [0.3.2 has hit PyPI](https://pypi.org/project/xpublish/0.3.2/). 

On the conda side of things, that will hopefully happen within the next 24 hours, and @ocepaf has created a [repo patch](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/485) so that it won't try to install earlier versions of Xpublish with Pydantic v2.
