### ISSUE TITLE
XPublish documentation link fails

### ISSUE THREAD

**Issue by jonmjoyce** [xpublish-community/xpublish#274]
The links to the documentation from the main page are not working: <https://xpublish.readthedocs.io/en/0.0.1/>

It looks like the version is not resolving correctly, because if I manually go to <https://xpublish.readthedocs.io/en/0.3.3/getting-started/index.html> then it works.

**Comment by jhamman** [comment]
Fixed! Thanks for the report @jonmjoyce.
